version: "3.4"

networks:
  SGCFT-dev:
    driver: bridge

services:
  SGCFT:
    image: SGCFT:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=SGCFT-db;username=SGCFT-db;password=SGCFT-db"
    networks:
      - SGCFT-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "SGCFT-db"
      POSTGRES_PASSWORD: "SGCFT-db"
      POSTGRES_DB: "SGCFT-db"
    networks:
      - SGCFT-dev
volumes:
  db_volume:
